# Contiki network configuration
MAKE_MAC = MAKE_MAC_CSMA


CONTIKI_PROJECT = client basestation login
APPS=serial-shell

all: $(CONTIKI_PROJECT)

CONTIKI = ../contiki-ng-wcnes
include $(CONTIKI)/Makefile.include